"""
Taiwan coastal live-camera catalogue.

Every entry here was verified by hand before inclusion: the stream reported
`is_live` and a real JPEG frame was pulled from it with ffmpeg.

Taiwan's agencies restart these streams on their own schedules, minting a NEW
YouTube video id each time - often daily. So nothing here stores a video id.
`channel` + `match` are the durable identifiers: the current id is resolved by
enumerating the channel's live streams and matching `match` against the title.

`loc_src` records where each coordinate came from, in descending order of trust:
  "operator open data (...)"  the operator's own published position
  "OSM ..."                   an OpenStreetMap feature for the named site
  "same site as ..."          positioned from a sibling camera at that site
None are camera mast positions - treat all as site-level.
"""

COASTAL_CAMERAS = {
    # --- CWA 中央氣象署 (the original nine) ---
    "keelung-heping": dict(
        en='Keelung Heping Island', zh='基隆和平島', match='基隆和平島',
        county='Various', coast='north', water='East China Sea',
        lat=25.1603, lon=121.7695, loc_src='OSM 和平島公園',
        operator='CWA 中央氣象署',
        channel='https://www.youtube.com/@cwa-tw/streams'),
    "keelung-bisha": dict(
        en='Keelung Bisha Fishing Port', zh='碧砂', match='碧砂',
        county='Various', coast='north', water='harbour',
        lat=25.14673, lon=121.78643, loc_src='OSM 碧砂漁港',
        operator='CWA 中央氣象署',
        channel='https://www.youtube.com/@cwa-tw/streams'),
    "longdong": dict(
        en='New Taipei Longdong', zh='龍洞', match='龍洞',
        county='Various', coast='northeast', water='Pacific',
        lat=25.0975, lon=121.9181, loc_src='CWA 龍洞潮位站',
        operator='CWA 中央氣象署',
        channel='https://www.youtube.com/@cwa-tw/streams'),
    "fulong": dict(
        en='New Taipei Fulong', zh='新北福隆', match='新北福隆',
        county='Various', coast='northeast', water='Pacific',
        lat=25.0217, lon=121.9503, loc_src='CWA 福隆潮位站',
        operator='CWA 中央氣象署',
        channel='https://www.youtube.com/@cwa-tw/streams'),
    "yilan-waiao": dict(
        en="Yilan Wai'ao", zh='宜蘭外澳', match='宜蘭外澳',
        county='Various', coast='east', water='Pacific',
        lat=24.87785, lon=121.84298, loc_src='OSM 外澳海灘',
        operator='CWA 中央氣象署',
        channel='https://www.youtube.com/@cwa-tw/streams'),
    "yilan-suao": dict(
        en='Yilan Suao Port', zh='宜蘭蘇澳', match='宜蘭蘇澳',
        county='Various', coast='east', water='harbour',
        lat=24.59247, lon=121.86577, loc_src='CWA 蘇澳潮位站',
        operator='CWA 中央氣象署',
        channel='https://www.youtube.com/@cwa-tw/streams'),
    "taitung-fugang": dict(
        en='Taitung Fugang Fishing Port', zh='臺東富岡漁港', match='臺東富岡漁港',
        county='Various', coast='east', water='harbour',
        lat=22.79084, lon=121.19049, loc_src='OSM 富岡漁港',
        operator='CWA 中央氣象署',
        channel='https://www.youtube.com/@cwa-tw/streams'),
    "tainan-anping": dict(
        en='Tainan Anping Port', zh='臺南安平港', match='臺南安平港',
        county='Various', coast='west', water='harbour',
        lat=22.99243, lon=120.15437, loc_src='OSM 安平漁港',
        operator='CWA 中央氣象署',
        channel='https://www.youtube.com/@cwa-tw/streams'),
    "hsinchu-cga": dict(
        en='Hsinchu Coast Guard (12th Sea Patrol)', zh='新竹', match='新竹',
        county='Various', coast='west', water='Taiwan Strait',
        lat=24.8486, lon=120.9206, loc_src='CWA 新竹潮位站',
        operator='CWA 中央氣象署',
        channel='https://www.youtube.com/@cwa-tw/streams'),

    "hualien-changhong": dict(
        en='Changhong Bridge Xiuguluan Mouth', zh='長虹橋', match=['長虹橋', 'Changhong Bridge'],
        county='Hualien', coast='east', water='rivermouth',
        lat=23.4667, lon=121.489, loc_src='operator open data (長虹橋)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "hualien-dashibi": dict(
        en='Dashibi Hill', zh='大石鼻山', match=['大石鼻山', 'Dashshibi', 'Dashibi'],
        county='Hualien', coast='east', water='headland',
        lat=23.6979, lon=121.552, loc_src='operator open data (大石鼻山)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "hualien-nanbin": dict(
        en='Nanbin Lookout', zh='南濱守望哨', match='南濱守望哨',
        county='Hualien', coast='east', water='seawall',
        lat=23.96247, lon=121.60699, loc_src='OSM 南濱守望哨',
        operator='WRA',
        channel='https://www.youtube.com/channel/UC8IKKTJkgZP9vdmnQDV-DZA/streams'),
    "hualien-qixingtan": dict(
        en='Qixingtan Checkpoint', zh='七星潭安檢所', match='七星潭安檢所',
        county='Hualien', coast='east', water='bay',
        lat=24.04164, lon=121.62221, loc_src='same site as hualien-qixingtan-beipu',
        operator='WRA',
        channel='https://www.youtube.com/channel/UC8IKKTJkgZP9vdmnQDV-DZA/streams'),
    "hualien-qixingtan-beipu": dict(
        en='Qixingtan Beipu Checkpoint', zh='北埔安檢所', match='北埔安檢所',
        county='Hualien', coast='east', water='bay',
        lat=24.04164, lon=121.62221, loc_src='OSM 北埔安檢所',
        operator='WRA',
        channel='https://www.youtube.com/channel/UC8IKKTJkgZP9vdmnQDV-DZA/streams'),
    "hualien-shitiping": dict(
        en='Shitiping', zh='石梯坪', match=['石梯坪', 'Shitiping'],
        county='Hualien', coast='east', water='rocky-coast',
        lat=23.4888, lon=121.514, loc_src='operator open data (石梯坪)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "hualien-wangyou": dict(
        en='Wangyou Pavilion', zh='忘憂亭', match='忘憂亭',
        county='Hualien', coast='east', water='coast',
        lat=23.96962, lon=121.61277, loc_src='OSM 忘憂亭',
        operator='WRA',
        channel='https://www.youtube.com/channel/UC8IKKTJkgZP9vdmnQDV-DZA/streams'),
    "penghu-guoye": dict(
        en='Guoye Sunrise Tower', zh='菓葉', match='菓葉',
        county='Penghu', coast='east', water='sea',
        lat=23.57837, lon=119.67888, loc_src='OSM 菓葉',
        operator='Penghu NSA',
        channel='https://www.youtube.com/channel/UCxTqE-VM_Tfe6pAjrJHMByQ/streams'),
    "penghu-kuibishan": dict(
        en='Kuibishan Moses Parting', zh='奎壁山', match='奎壁山',
        county='Penghu', coast='east', water='tidal-causeway',
        lat=23.55841, lon=119.6031, loc_src='operator open data (奎壁山)',
        operator='Penghu NSA',
        channel='https://www.youtube.com/channel/UCxTqE-VM_Tfe6pAjrJHMByQ/streams'),
    "taitung-fanchuanbi": dict(
        en='Green Island Fanchuanbi', zh='帆船鼻', match=['帆船鼻', 'Fanchuanbi'],
        county='Taitung', coast='east', water='cliff',
        lat=22.6354, lon=121.507, loc_src='operator open data (帆船鼻)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "taitung-fugang-county": dict(
        en='Fugang Port Taitung County', zh='富岡漁港', match='富岡漁港',
        county='Taitung', coast='east', water='ferry-port',
        lat=22.79084, lon=121.19049, loc_src='OSM 富岡漁港',
        operator='Taitung County',
        channel='https://www.youtube.com/channel/UCT4jEYvUdpdN9oUALaypGfQ/streams'),
    "taitung-greenisland-chaikou": dict(
        en='Green Island Chaikou', zh='綠島柴口', match=['柴口', 'Chaikou Snorkeling'],
        county='Taitung', coast='east', water='reef',
        lat=22.6767, lon=121.483, loc_src='operator open data (綠島柴口)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "taitung-greenisland-nanliao": dict(
        en='Green Island Nanliao Harbour', zh='綠島南寮', match=['南寮漁港', 'Nanliao Fishing Harbor'],
        county='Taitung', coast='east', water='harbour',
        lat=22.6601, lon=121.474, loc_src='operator open data (綠島南寮)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "taitung-jialulan": dict(
        en='Jialulan', zh='加路蘭', match=['加路蘭', 'Jialulan'],
        county='Taitung', coast='east', water='coast',
        lat=22.8068, lon=121.197, loc_src='operator open data (加路蘭)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "taitung-jinzun": dict(
        en='Jinzun Surf Point', zh='金樽', match=['金樽', 'Jinzun'],
        county='Taitung', coast='east', water='surf',
        lat=22.9451, lon=121.28, loc_src='operator open data (金樽)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "taitung-jinzun-county": dict(
        en='Jinzun Taitung County', zh='台東金樽', match='台東金樽',
        county='Taitung', coast='east', water='surf',
        lat=22.96318, lon=121.29424, loc_src='OSM 台東金樽',
        operator='Taitung County',
        channel='https://www.youtube.com/channel/UCT4jEYvUdpdN9oUALaypGfQ/streams'),
    "taitung-sanxiantai": dict(
        en='Sanxiantai', zh='三仙台', match=['三仙台', 'Sanxiantai'],
        county='Taitung', coast='east', water='islet',
        lat=23.1232, lon=121.407, loc_src='operator open data (三仙台)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "taitung-torik": dict(
        en='Torik Visitor Centre', zh='都歷', match=['都歷', 'Torik'],
        county='Taitung', coast='east', water='coast',
        lat=23.0204, lon=121.325, loc_src='operator open data (都歷)',
        operator='East Coast NSA',
        channel='https://www.youtube.com/channel/UC5FiBoG6GcB5QqsiOsGe22A/streams'),
    "yilan-hexing": dict(
        en='Toucheng Hexing', zh='頭城合興', match='頭城合興',
        county='Yilan', coast='east', water='beach',
        lat=24.91813, lon=121.88397, loc_src='OSM 頭城合興',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "yilan-nanfangao1": dict(
        en='Nanfangao 1st Fishing Port', zh='南方澳第一漁港', match='南方澳第一漁港',
        county='Yilan', coast='east', water='harbour',
        lat=24.58528, lon=121.86656, loc_src='same site as yilan-nanfangao3',
        operator='private',
        channel='https://www.youtube.com/channel/UCRFKY6zRG17tBT1tktsFiVg/streams'),
    "yilan-nanfangao2": dict(
        en='Nanfangao 2nd Fishing Port', zh='南方澳第二漁港', match='南方澳第二漁港',
        county='Yilan', coast='east', water='harbour',
        lat=24.58528, lon=121.86656, loc_src='same site as yilan-nanfangao3',
        operator='private',
        channel='https://www.youtube.com/channel/UCRFKY6zRG17tBT1tktsFiVg/streams'),
    "yilan-nanfangao3": dict(
        en='Nanfangao 3rd Fishing Port', zh='南方澳第三漁港', match='南方澳第三漁港',
        county='Yilan', coast='east', water='harbour',
        lat=24.58528, lon=121.86656, loc_src='OSM 南方澳第三漁港',
        operator='private',
        channel='https://www.youtube.com/channel/UCRFKY6zRG17tBT1tktsFiVg/streams'),
    "yilan-toucheng-s": dict(
        en='Toucheng Coastal Park South', zh='頭城濱海', match='頭城濱海',
        county='Yilan', coast='east', water='beach',
        lat=24.91813, lon=121.88397, loc_src='OSM 頭城濱海',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "yilan-waiao-para": dict(
        en='Waiao Paragliding Base', zh='外澳飛行傘', match='外澳飛行傘',
        county='Yilan', coast='east', water='beach',
        lat=24.87882, lon=121.83435, loc_src='OSM 外澳飛行傘',
        operator='Northeast Coast NSA',
        channel='https://www.youtube.com/channel/UC4lv0ulMa_wgbZ5ystZxVpQ/streams'),
    "yilan-wuweigang": dict(
        en='Wuweigang Wetland', zh='無尾港', match='無尾港',
        county='Yilan', coast='east', water='rivermouth',
        lat=24.61765, lon=121.85429, loc_src='OSM 無尾港',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "yilan-yongzhen": dict(
        en='Yongzhen Coastal Station', zh='永鎮', match='永鎮',
        county='Yilan', coast='east', water='beach',
        lat=24.77143, lon=121.81561, loc_src='OSM 永鎮',
        operator='Northeast Coast NSA',
        channel='https://www.youtube.com/channel/UC4lv0ulMa_wgbZ5ystZxVpQ/streams'),
    "keelung-chaojing": dict(
        en='Chaojing Bay', zh='潮境', match='潮境',
        county='Keelung', coast='north', water='bay',
        lat=25.14341, lon=121.80339, loc_src='OSM 潮境',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "keelung-chaojing3": dict(
        en='Chaojing Bay 3', zh='潮境', match='潮境',
        county='Keelung', coast='north', water='bay',
        lat=25.14341, lon=121.80339, loc_src='OSM 潮境',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "keelung-heping-park": dict(
        en='Heping Island Park', zh='和平島公園', match='和平島公園',
        county='Keelung', coast='north', water='geopark',
        lat=25.1603, lon=121.7695, loc_src='OSM 和平島公園',
        operator='North Coast NSA',
        channel='https://www.youtube.com/channel/UC0mfEc84Gk0bfYIzntXGTIQ/streams'),
    "keelung-maritime-plaza": dict(
        en='Keelung Maritime Plaza', zh='海洋廣場', match='海洋廣場',
        county='Keelung', coast='north', water='harbour-basin',
        lat=25.15047, lon=121.7751, loc_src='OSM 海洋廣場',
        operator='private broadcaster',
        channel='https://www.youtube.com/channel/UCCvQqg1UKGP1Wshak1078hw/streams'),
    "keelung-waimushan": dict(
        en='Waimushan', zh='外木山', match='外木山',
        county='Keelung', coast='north', water='rocky-coast',
        lat=25.15434, lon=121.7333, loc_src='OSM 外木山',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "ntpc-baishawan": dict(
        en='Baisha Bay', zh='白沙灣', match='白沙灣',
        county='New Taipei', coast='north', water='beach',
        lat=25.2848, lon=121.51477, loc_src='OSM 白沙灣',
        operator='North Coast NSA',
        channel='https://www.youtube.com/channel/UC0mfEc84Gk0bfYIzntXGTIQ/streams'),
    "ntpc-guanyinshan": dict(
        en='Guanyinshan Tamsui Mouth', zh='觀音山', match='觀音山',
        county='New Taipei', coast='north', water='rivermouth',
        lat=25.13594, lon=121.42668, loc_src='OSM 觀音山',
        operator='North Coast NSA',
        channel='https://www.youtube.com/channel/UC0mfEc84Gk0bfYIzntXGTIQ/streams'),
    "ntpc-jhongjiao": dict(
        en='Jhongjiao Bay', zh='中角灣', match='中角灣',
        county='New Taipei', coast='north', water='surf',
        lat=25.239, lon=121.63234, loc_src='OSM 中角灣',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "ntpc-jhongjiao-4k": dict(
        en='Jhongjiao Bay 4K', zh='中角灣', match='中角灣',
        county='New Taipei', coast='north', water='surf',
        lat=25.239, lon=121.63234, loc_src='OSM 中角灣',
        operator='North Coast NSA',
        channel='https://www.youtube.com/channel/UC0mfEc84Gk0bfYIzntXGTIQ/streams'),
    "ntpc-laomei": dict(
        en='Laomei Green Reef', zh='老梅', match='老梅',
        county='New Taipei', coast='north', water='reef',
        lat=25.28813, lon=121.54575, loc_src='OSM 老梅',
        operator='North Coast NSA',
        channel='https://www.youtube.com/channel/UC0mfEc84Gk0bfYIzntXGTIQ/streams'),
    "ntpc-wanli": dict(
        en='Wanli Fishing Port', zh='萬里漁港', match='萬里漁港',
        county='New Taipei', coast='north', water='harbour',
        lat=25.18047, lon=121.69601, loc_src='OSM 萬里漁港',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "ntpc-yehliu": dict(
        en='Yehliu Geopark', zh='野柳', match='野柳',
        county='New Taipei', coast='north', water='headland',
        lat=25.2039, lon=121.68865, loc_src='OSM 野柳',
        operator='North Coast NSA',
        channel='https://www.youtube.com/channel/UC0mfEc84Gk0bfYIzntXGTIQ/streams'),
    "ntpc-yehliu-underwater": dict(
        en='Yehliu Neptune Pier Underwater', zh='海王星碼頭', match='海王星碼頭',
        county='New Taipei', coast='north', water='underwater',
        lat=25.2039, lon=121.68865, loc_src='same site as ntpc-yehliu',
        operator='North Coast NSA',
        channel='https://www.youtube.com/channel/UC0mfEc84Gk0bfYIzntXGTIQ/streams'),
    "ntpc-bitou": dict(
        en='Bitou Cape', zh='鼻頭', match='鼻頭',
        county='New Taipei', coast='northeast', water='cape',
        lat=25.12477, lon=121.91656, loc_src='OSM 鼻頭',
        operator='Northeast Coast NSA',
        channel='https://www.youtube.com/channel/UC4lv0ulMa_wgbZ5ystZxVpQ/streams'),
    "ntpc-fulong-bay": dict(
        en='Fulong Bay', zh='福隆海灣', match='福隆海灣',
        county='New Taipei', coast='northeast', water='lagoon',
        lat=25.01295, lon=121.55259, loc_src='OSM 福隆海灣',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "ntpc-fulong-beach": dict(
        en='Fulong Beach', zh='福隆海水浴場', match='福隆海水浴場',
        county='New Taipei', coast='northeast', water='beach',
        lat=25.02225, lon=121.94275, loc_src='OSM 福隆海水浴場',
        operator='Northeast Coast NSA',
        channel='https://www.youtube.com/channel/UC4lv0ulMa_wgbZ5ystZxVpQ/streams'),
    "ntpc-longdong-obs": dict(
        en='Longdong Bay Observatory', zh='龍洞灣', match='龍洞灣',
        county='New Taipei', coast='northeast', water='bay',
        lat=25.11804, lon=121.92055, loc_src='OSM 龍洞灣',
        operator='Northeast Coast NSA',
        channel='https://www.youtube.com/channel/UC4lv0ulMa_wgbZ5ystZxVpQ/streams'),
    "ntpc-longdong-sijiwan": dict(
        en='Longdong Sijiwan', zh='龍洞四季灣', match='龍洞四季灣',
        county='New Taipei', coast='northeast', water='bay',
        lat=25.10121, lon=121.91828, loc_src='OSM 龍洞四季灣',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "ntpc-magang": dict(
        en='Magang Post', zh='馬崗', match='馬崗',
        county='New Taipei', coast='northeast', water='coast',
        lat=25.01336, lon=122.00246, loc_src='OSM 馬崗',
        operator='Northeast Coast NSA',
        channel='https://www.youtube.com/channel/UC4lv0ulMa_wgbZ5ystZxVpQ/streams'),
    "ntpc-shicheng": dict(
        en='Shicheng Fishing Port', zh='石城漁港', match='石城漁港',
        county='New Taipei', coast='northeast', water='harbour',
        lat=25.0489, lon=121.58189, loc_src='OSM 石城漁港',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "ntpc-shicheng1": dict(
        en='Shicheng Fishing Port 1', zh='石城漁港', match='石城漁港',
        county='New Taipei', coast='northeast', water='harbour',
        lat=25.0489, lon=121.58189, loc_src='OSM 石城漁港',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "yilan-caoling": dict(
        en='Old Caoling Tunnel South Portal', zh='舊草嶺', match='舊草嶺',
        county='Yilan', coast='northeast', water='coast',
        lat=24.98805, lon=121.9562, loc_src='OSM 舊草嶺',
        operator='Northeast Coast NSA',
        channel='https://www.youtube.com/channel/UC4lv0ulMa_wgbZ5ystZxVpQ/streams'),
    "ntpc-tamsui-wharf": dict(
        en='Tamsui Fishermans Wharf', zh='淡水漁人碼頭', match='淡水漁人碼頭',
        county='New Taipei', coast='northwest', water='rivermouth',
        lat=25.182, lon=121.41861, loc_src='OSM 淡水漁人碼頭',
        operator='New Taipei Tourism',
        channel='https://www.youtube.com/channel/UCm8_3Nf9LFmPwuKSvYhhwLw/streams'),
    "pingtung-chuanfanshi": dict(
        en='Chuanfanshi Sail Rock', zh='船帆石', match='船帆石',
        county='Pingtung', coast='south', water='reef',
        lat=21.93361, lon=120.82389, loc_src='OSM 船帆石',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "pingtung-guanhai": dict(
        en='Kenting Guanhai Tower', zh='觀海樓', match='觀海樓',
        county='Pingtung', coast='south', water='sea-view',
        lat=21.96665, lon=120.81554, loc_src='OSM 觀海樓',
        operator='Forestry Agency',
        channel='https://www.youtube.com/channel/UCOvjqsgwf8RFMmyj7QIQhSg/streams'),
    "pingtung-houbihu-knp": dict(
        en='Houbihu Yacht Harbour', zh='後壁湖', match='後壁湖',
        county='Pingtung', coast='south', water='harbour',
        lat=22.04333, lon=120.71722, loc_src='OSM 後壁湖',
        operator='Kenting National Park',
        channel='https://www.youtube.com/channel/UC7RyAGaxzAI9dD8NINv653w/streams'),
    "pingtung-houbihu1": dict(
        en='Houbihu Harbour 1', zh='後壁湖', match='後壁湖',
        county='Pingtung', coast='south', water='harbour',
        lat=22.04333, lon=120.71722, loc_src='OSM 後壁湖',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "pingtung-houbihu2": dict(
        en='Houbihu Harbour 2', zh='後壁湖', match='後壁湖',
        county='Pingtung', coast='south', water='harbour',
        lat=22.04333, lon=120.71722, loc_src='OSM 後壁湖',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "pingtung-jialeshui": dict(
        en='Jialeshui Reef', zh='佳樂水', match='佳樂水',
        county='Pingtung', coast='south', water='surf',
        lat=21.99389, lon=120.86361, loc_src='OSM 佳樂水',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "pingtung-nanwan": dict(
        en='Kenting Nanwan', zh='南灣', match='南灣',
        county='Pingtung', coast='south', water='bay',
        lat=21.95944, lon=120.76639, loc_src='OSM 南灣',
        operator='private BnB',
        channel='https://www.youtube.com/channel/UCpOav19GgbSHnP2iwOa5Y2Q/streams'),
    "pingtung-sailrock-beach": dict(
        en='Sail Rock Beach 4K', zh='船帆石沙灘', match='船帆石沙灘',
        county='Pingtung', coast='south', water='beach',
        lat=21.93529, lon=120.82082, loc_src='OSM 船帆石沙灘',
        operator='Kenting National Park',
        channel='https://www.youtube.com/channel/UC7RyAGaxzAI9dD8NINv653w/streams'),
    "pingtung-shejiekeng1": dict(
        en='Shejiekeng Bay 1', zh='社皆坑', match='社皆坑',
        county='Pingtung', coast='south', water='bay',
        lat=22.1325, lon=120.70556, loc_src='OSM 社皆坑',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "pingtung-shejiekeng2": dict(
        en='Shejiekeng Bay 2', zh='社皆坑', match='社皆坑',
        county='Pingtung', coast='south', water='bay',
        lat=22.1325, lon=120.70556, loc_src='OSM 社皆坑',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "pingtung-bayfun-land": dict(
        en='Bayfun Land Tidal Inlet', zh='潮口平台', match='潮口平台',
        county='Pingtung', coast='southwest', water='inlet',
        lat=22.45259, lon=120.45907, loc_src='OSM 潮口平台',
        operator='Dapeng Bay NSA',
        channel='https://www.youtube.com/channel/UCmrGc9x8bm9gG4dQGYlf27w/streams'),
    "pingtung-bayfun-pier": dict(
        en='Bayfun Pier', zh='濱灣之心', match='濱灣之心',
        county='Pingtung', coast='southwest', water='lagoon',
        lat=22.43952, lon=120.47491, loc_src='OSM 濱灣之心',
        operator='Dapeng Bay NSA',
        channel='https://www.youtube.com/channel/UCmrGc9x8bm9gG4dQGYlf27w/streams'),
    "pingtung-dafuxi": dict(
        en='Dafuxi', zh='大福西', match='大福西',
        county='Pingtung', coast='southwest', water='lagoon',
        lat=24.21515, lon=121.6701, loc_src='OSM 大福西',
        operator='Dapeng Bay NSA',
        channel='https://www.youtube.com/channel/UCmrGc9x8bm9gG4dQGYlf27w/streams'),
    "pingtung-dapeng-c": dict(
        en='Dapeng Bay Marina Zone C', zh='濱灣碼頭C堤', match='濱灣碼頭C堤',
        county='Pingtung', coast='southwest', water='marina',
        lat=22.43783, lon=120.47608, loc_src='same site as pingtung-dapeng-marina',
        operator='Dapeng Bay NSA',
        channel='https://www.youtube.com/channel/UCmrGc9x8bm9gG4dQGYlf27w/streams'),
    "pingtung-dapeng-d": dict(
        en='Dapeng Bay Marina Zone D', zh='濱灣碼頭D堤', match='濱灣碼頭D堤',
        county='Pingtung', coast='southwest', water='marina',
        lat=22.43783, lon=120.47608, loc_src='same site as pingtung-dapeng-marina',
        operator='Dapeng Bay NSA',
        channel='https://www.youtube.com/channel/UCmrGc9x8bm9gG4dQGYlf27w/streams'),
    "pingtung-dapeng-marina": dict(
        en='Dapeng Bay Marina', zh='濱灣碼頭', match='濱灣碼頭',
        county='Pingtung', coast='southwest', water='marina',
        lat=22.43783, lon=120.47608, loc_src='OSM 濱灣碼頭',
        operator='Dapeng Bay NSA',
        channel='https://www.youtube.com/channel/UCmrGc9x8bm9gG4dQGYlf27w/streams'),
    "pingtung-nmmb": dict(
        en='National Museum Marine Biology', zh='海生館', match='海生館',
        county='Pingtung', coast='southwest', water='shore',
        lat=22.04592, lon=120.69844, loc_src='OSM 海生館',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "pingtung-vaserock": dict(
        en='Vase Rock Xiaoliuqiu', zh='花瓶岩', match='花瓶岩',
        county='Pingtung', coast='southwest', water='reef',
        lat=22.35568, lon=120.38073, loc_src='OSM 花瓶岩',
        operator='Dapeng Bay NSA',
        channel='https://www.youtube.com/channel/UCmrGc9x8bm9gG4dQGYlf27w/streams'),
    "pingtung-wanghai": dict(
        en='Wanghai Pavilion', zh='望海亭', match='望海亭',
        county='Pingtung', coast='southwest', water='sea',
        lat=22.35318, lon=120.3732, loc_src='OSM 望海亭',
        operator='Dapeng Bay NSA',
        channel='https://www.youtube.com/channel/UCmrGc9x8bm9gG4dQGYlf27w/streams'),
    "pingtung-youyiqu": dict(
        en='Youyiqu Visitor Centre', zh='遊一區', match='遊一區',
        county='Pingtung', coast='southwest', water='lagoon',
        lat=22.43783, lon=120.47608, loc_src='same site as pingtung-dapeng-marina',
        operator='Dapeng Bay NSA',
        channel='https://www.youtube.com/channel/UCmrGc9x8bm9gG4dQGYlf27w/streams'),
    "changhua-dolphin": dict(
        en='Changhua White Dolphin House', zh='白色海豚屋', match='白色海豚屋',
        county='Changhua', coast='west', water='mudflat',
        lat=23.96904, lon=120.32455, loc_src='same site as changhua-wanggong',
        operator='Changhua County',
        channel='https://www.youtube.com/channel/UCcq-jAioupQTR_Oiwm2gglw/streams'),
    "changhua-wanggong": dict(
        en='Wanggong Fishing Port', zh='王功漁港', match='王功漁港',
        county='Changhua', coast='west', water='harbour',
        lat=23.96904, lon=120.32455, loc_src='OSM 王功漁港',
        operator='Changhua County',
        channel='https://www.youtube.com/channel/UCcq-jAioupQTR_Oiwm2gglw/streams'),
    "chiayi-budai": dict(
        en='Budai Port', zh='布袋港', match='布袋港',
        county='Chiayi', coast='west', water='port',
        lat=23.38136, lon=120.15666, loc_src='OSM 布袋港',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "chiayi-budai-wetland1": dict(
        en='Budai Wetland Eco Park 1', zh='布袋溼地生態園區', match='布袋溼地生態園區',
        county='Chiayi', coast='west', water='wetland',
        lat=23.3668, lon=120.179, loc_src='operator open data (布袋溼地生態園區)',
        operator='Southwest Coast NSA',
        channel='https://www.youtube.com/channel/UCaRiBe_GoFpJ8LKIedTY96g/streams'),
    "chiayi-budai-wetland2": dict(
        en='Budai Wetland Eco Park 2', zh='布袋溼地生態園區', match='布袋溼地生態園區',
        county='Chiayi', coast='west', water='wetland',
        lat=23.3668, lon=120.179, loc_src='operator open data (布袋溼地生態園區)',
        operator='Southwest Coast NSA',
        channel='https://www.youtube.com/channel/UCr448AeVVqeD242Dnnh376Q/streams'),
    "chiayi-dongshi": dict(
        en='Dongshi Fishermans Wharf', zh='東石漁人碼頭', match='東石漁人碼頭',
        county='Chiayi', coast='west', water='lagoon',
        lat=23.45206, lon=120.13648, loc_src='OSM 東石漁人碼頭',
        operator='Chiayi County',
        channel='https://www.youtube.com/channel/UCqCmgkzXxyQ9s6MRqKbz3nw/streams'),
    "chiayi-xincen": dict(
        en='Xincen Park', zh='新岑公園', match='新岑公園',
        county='Chiayi', coast='west', water='wetland',
        lat=23.3421, lon=120.172, loc_src='operator open data (新岑公園)',
        operator='Southwest Coast NSA',
        channel='https://www.youtube.com/channel/UC_iT67K_49E8LrPpEq6F2RQ/streams'),
    "hsinchu-crescent": dict(
        en='Crescent Bay Sea Deck', zh='新月沙灣', match='新月沙灣',
        county='Hsinchu', coast='west', water='beach',
        lat=24.86441, lon=120.93975, loc_src='OSM 新月沙灣',
        operator='Zhubei City',
        channel='https://www.youtube.com/channel/UCqv4mqa4LRLYNTwxaRo9-qg/streams'),
    "kaohsiung-cijin": dict(
        en='Cijin', zh='旗津', match='旗津',
        county='Kaohsiung', coast='west', water='harbour',
        lat=22.60825, lon=120.27142, loc_src='OSM 旗津',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "kaohsiung-cijin-beach": dict(
        en='Cijin Beach', zh='旗津海水浴場', match='旗津海水浴場',
        county='Kaohsiung', coast='west', water='beach',
        lat=22.60712, lon=120.26908, loc_src='OSM 旗津海水浴場',
        operator='Kaohsiung Travel',
        channel='https://www.youtube.com/channel/UC2lamMZjjT-Qcq-zIx6NrCw/streams'),
    "kaohsiung-dagang": dict(
        en='Great Harbor Bridge', zh='大港橋', match='大港橋',
        county='Kaohsiung', coast='west', water='harbour-basin',
        lat=22.61788, lon=120.28388, loc_src='OSM 大港橋',
        operator='Kaohsiung City',
        channel='https://www.youtube.com/channel/UCLLSFZWVFKf0bIph0x9vTjg/streams'),
    "kaohsiung-keliao": dict(
        en='Keliao Coast', zh='蚵寮', match='蚵寮',
        county='Kaohsiung', coast='west', water='seawall',
        lat=22.95183, lon=120.54146, loc_src='OSM 蚵寮',
        operator='WRA',
        channel='https://www.youtube.com/channel/UC8IKKTJkgZP9vdmnQDV-DZA/streams'),
    "kaohsiung-port2": dict(
        en='Kaohsiung Port 2nd Entrance', zh='第二港口', match='第二港口',
        county='Kaohsiung', coast='west', water='port-channel',
        lat=22.5395, lon=120.3055, loc_src='operator open data (第二港口)',
        operator='Kaohsiung Cultural Affairs',
        channel='https://www.youtube.com/channel/UC4hhZs_2_pVlENFLSQT7YPw/streams'),
    "kaohsiung-shoushan": dict(
        en='Shoushan Lovers Platform', zh='壽山情人觀景台', match='壽山情人觀景台',
        county='Kaohsiung', coast='west', water='port-mouth',
        lat=22.62549, lon=120.27397, loc_src='OSM 壽山情人觀景台',
        operator='Kaohsiung Travel',
        channel='https://www.youtube.com/channel/UC2lamMZjjT-Qcq-zIx6NrCw/streams'),
    "kinmen-134": dict(
        en='Kinmen 134 Highland', zh='134高地', match='134高地',
        county='Kinmen', coast='west', water='coast',
        lat=24.42736, lon=118.29998, loc_src='same site as kinmen-jiangong',
        operator='Kinmen County',
        channel='https://www.youtube.com/channel/UC6LcWhmbz6dbPtrIZXJn79A/streams'),
    "kinmen-jiangong": dict(
        en='Jiangong Islet', zh='建功嶼', match='建功嶼',
        county='Kinmen', coast='west', water='tidal-causeway',
        lat=24.42736, lon=118.29998, loc_src='OSM 建功嶼',
        operator='Kinmen County',
        channel='https://www.youtube.com/channel/UC6LcWhmbz6dbPtrIZXJn79A/streams'),
    "kinmen-liaoluo": dict(
        en='Liaoluo Port', zh='料羅港', match='料羅港',
        county='Kinmen', coast='west', water='port',
        lat=24.40982, lon=118.42816, loc_src='OSM 料羅港',
        operator='Kinmen County',
        channel='https://www.youtube.com/channel/UC6LcWhmbz6dbPtrIZXJn79A/streams'),
    "matsu-dongyin": dict(
        en='Dongyin Zhongzhu Port', zh='中柱港', match='中柱港',
        county='Lienchiang', coast='west', water='ferry-port',
        lat=26.36497, lon=120.48272, loc_src='OSM 中柱港',
        operator='Dongyin Township',
        channel='https://www.youtube.com/channel/UCzAS1KVwayK_487tcs9UHkA/streams'),
    "matsu-tiebao": dict(
        en='Nangan Tiebao', zh='鐵堡', match='鐵堡',
        county='Lienchiang', coast='west', water='rocky-coast',
        lat=26.14187, lon=119.92092, loc_src='OSM 鐵堡',
        operator='Matsu NSA',
        channel='https://www.youtube.com/channel/UC-872EuZ5fJZvl0PJdJg3Mw/streams'),
    "miaoli-haowangjiao": dict(
        en='Houlong Haowangjiao', zh='好望角', match='好望角',
        county='Miaoli', coast='west', water='cliff',
        lat=24.59745, lon=120.73071, loc_src='OSM 好望角',
        operator='Miaoli County',
        channel='https://www.youtube.com/channel/UC9SsBCtiL23fj0Xyyt7dRtw/streams'),
    "miaoli-tongxiao": dict(
        en='Tongxiao Sunset Boulevard', zh='落日大道', match='落日大道',
        county='Miaoli', coast='west', water='beach',
        lat=24.5425, lon=120.70196, loc_src='OSM 落日大道',
        operator='Miaoli County',
        channel='https://www.youtube.com/channel/UC9SsBCtiL23fj0Xyyt7dRtw/streams'),
    "penghu-aimen": dict(
        en='Aimen', zh='隘門', match='隘門',
        county='Penghu', coast='west', water='beach',
        lat=23.56235, lon=119.63647, loc_src='OSM 隘門',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "penghu-aimen-beach": dict(
        en='Aimen Beach', zh='隘門沙灘', match='隘門沙灘',
        county='Penghu', coast='west', water='beach',
        lat=23.55685, lon=119.64025, loc_src='OSM 隘門沙灘',
        operator='Penghu NSA',
        channel='https://www.youtube.com/channel/UCxTqE-VM_Tfe6pAjrJHMByQ/streams'),
    "penghu-dongyuping": dict(
        en='Dongyuping Islet', zh='東嶼坪', match='東嶼坪',
        county='Penghu', coast='west', water='island',
        lat=23.26063, lon=119.51523, loc_src='OSM 東嶼坪',
        operator='Marine NP HQ',
        channel='https://www.youtube.com/channel/UCM_xhbsUHkqIayYYPEULN0Q/streams'),
    "penghu-fengzhengping": dict(
        en='Fengzhengping', zh='風箏坪', match='風箏坪',
        county='Penghu', coast='west', water='beach',
        lat=24.11386, lon=120.70364, loc_src='OSM 風箏坪',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "penghu-guanyinting1": dict(
        en='Guanyinting Bay 1', zh='觀音亭', match='觀音亭',
        county='Penghu', coast='west', water='bay',
        lat=23.56761, lon=119.56197, loc_src='OSM 觀音亭',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "penghu-guanyinting2": dict(
        en='Guanyinting Bay 2', zh='觀音亭', match='觀音亭',
        county='Penghu', coast='west', water='bay',
        lat=23.56761, lon=119.56197, loc_src='OSM 觀音亭',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "penghu-hejie": dict(
        en='Hejie', zh='合界', match='合界',
        county='Penghu', coast='west', water='bay',
        lat=23.63868, lon=119.52935, loc_src='OSM 合界',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "penghu-neian": dict(
        en='Neian Recreation Area', zh='內垵', match='內垵',
        county='Penghu', coast='west', water='bay',
        lat=23.57083, lon=119.50139, loc_src='OSM 內垵',
        operator='Penghu NSA',
        channel='https://www.youtube.com/channel/UCxTqE-VM_Tfe6pAjrJHMByQ/streams'),
    "penghu-qimei-nanhu": dict(
        en='Qimei Nanhu Harbour', zh='南滬港', match='南滬港',
        county='Penghu', coast='west', water='harbour',
        lat=23.1946, lon=119.41882, loc_src='OSM 南滬港',
        operator='Penghu NSA',
        channel='https://www.youtube.com/channel/UCxTqE-VM_Tfe6pAjrJHMByQ/streams'),
    "penghu-qingwan": dict(
        en='Qingwan', zh='青灣', match='青灣',
        county='Penghu', coast='west', water='bay',
        lat=23.52662, lon=119.55646, loc_src='OSM 青灣',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "penghu-suogang": dict(
        en='Suogang Bay', zh='鎖港', match='鎖港',
        county='Penghu', coast='west', water='harbour',
        lat=23.52443, lon=119.60135, loc_src='OSM 鎖港',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "pingtung-fangliao": dict(
        en='Fangliao Fishing Port', zh='枋寮漁港', match='枋寮漁港',
        county='Pingtung', coast='west', water='harbour',
        lat=22.36364, lon=120.59412, loc_src='OSM 枋寮漁港',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "pingtung-linbian": dict(
        en='Linbian River Jiangyuan Drainage', zh='羌園排水', match='羌園排水',
        county='Pingtung', coast='west', water='rivermouth',
        lat=22.43831, lon=120.54079, loc_src='OSM 羌園排水',
        operator='WRA',
        channel='https://www.youtube.com/channel/UC8IKKTJkgZP9vdmnQDV-DZA/streams'),
    "pingtung-shanhai": dict(
        en='Shanhai Fishing Port', zh='山海漁港', match='山海漁港',
        county='Pingtung', coast='west', water='harbour',
        lat=21.98559, lon=120.71163, loc_src='OSM 山海漁港',
        operator='private dive shop',
        channel='https://www.youtube.com/channel/UCT0SJ3qnfe7Y3wUiyb4rxPw/streams'),
    "taichung-gaomei": dict(
        en='Gaomei Wetland', zh='高美濕地', match='高美濕地',
        county='Taichung', coast='west', water='mudflat',
        lat=24.31187, lon=120.55118, loc_src='OSM 高美濕地',
        operator='Taichung Tourism Bureau',
        channel='https://www.youtube.com/channel/UCSV_89hkpo3y_J1INMueN6A/streams'),
    "tainan-beimen-lagoon": dict(
        en='Beimen Lagoon', zh='北門潟湖', match='北門潟湖',
        county='Tainan', coast='west', water='lagoon',
        lat=23.2588, lon=120.108, loc_src='operator open data (北門潟湖)',
        operator='Southwest Coast NSA',
        channel='https://www.youtube.com/channel/UCLgYRhzthXWRxWXgVhfvXcA/streams'),
    "tainan-beishanwei": dict(
        en='Beishanwei Waterfowl Reserve', zh='北汕尾', match='北汕尾',
        county='Tainan', coast='west', water='tidal-flat',
        lat=23.02223, lon=120.14367, loc_src='OSM 北汕尾',
        operator='Taijiang National Park',
        channel='https://www.youtube.com/channel/UCfj69ny_nODRdJMSgyk-O4g/streams'),
    "tainan-golden-coast": dict(
        en='Golden Coast', zh='黃金海岸', match='黃金海岸',
        county='Tainan', coast='west', water='seawall',
        lat=22.93175, lon=120.1763, loc_src='OSM 黃金海岸',
        operator='WRA',
        channel='https://www.youtube.com/channel/UC8IKKTJkgZP9vdmnQDV-DZA/streams'),
    "tainan-guanxi": dict(
        en='Anping Guanxi Platform', zh='安平觀夕平台', match='安平觀夕平台',
        county='Tainan', coast='west', water='beach',
        lat=22.98975, lon=120.14713, loc_src='OSM 安平觀夕平台',
        operator='NAMR GoOcean',
        channel='https://www.youtube.com/channel/UCk6tCE_LR8tzJCk8MWEPO6A/streams'),
    "tainan-jingzijiao": dict(
        en='Jingzijiao Salt Fields', zh='井仔腳', match='井仔腳',
        county='Tainan', coast='west', water='saltpan',
        lat=23.2588, lon=120.108, loc_src='operator open data (井仔腳)',
        operator='Southwest Coast NSA',
        channel='https://www.youtube.com/channel/UCixTe_kejs3Uvq0Ay5bFfYA/streams'),
    "tainan-liukong": dict(
        en='Liukong Wharf Qigu Lagoon', zh='六孔碼頭', match='六孔碼頭',
        county='Tainan', coast='west', water='lagoon',
        lat=23.12372, lon=120.07869, loc_src='OSM 六孔碼頭',
        operator='Taijiang National Park',
        channel='https://www.youtube.com/channel/UCfj69ny_nODRdJMSgyk-O4g/streams'),
    "tainan-qigu": dict(
        en='Qigu Spoonbill Pavilion', zh='七股賞鳥亭', match='七股賞鳥亭',
        county='Tainan', coast='west', water='lagoon',
        lat=23.07904, lon=120.05208, loc_src='OSM 七股賞鳥亭',
        operator='Taijiang National Park',
        channel='https://www.youtube.com/channel/UCfj69ny_nODRdJMSgyk-O4g/streams'),
    "taoyuan-xucuogang": dict(
        en='Xucuogang Wetland', zh='許厝港', match='許厝港',
        county='Taoyuan', coast='west', water='wetland',
        lat=25.0851, lon=121.17373, loc_src='OSM 許厝港',
        operator='Taoyuan City Tourism',
        channel='https://www.youtube.com/channel/UCARB8y6PuoOBjZXJKIG-LDw/streams'),
    "taoyuan-yongan": dict(
        en='Yongan Fishing Harbour', zh='永安漁港', match='永安漁港',
        county='Taoyuan', coast='west', water='harbour',
        lat=24.98913, lon=121.01257, loc_src='OSM 永安漁港',
        operator='Taoyuan City Tourism',
        channel='https://www.youtube.com/channel/UCARB8y6PuoOBjZXJKIG-LDw/streams'),
}
